# BharathVA Feed Service - Simple Message Storage Configuration

server:
  port: ${SERVER_PORT:8082}

# Spring Configuration
spring:
  # MongoDB Configuration
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://nishalpoojary66_db_user:mJjqxxMVtfnb6keW@message-cluster.m8hycwy.mongodb.net/?retryWrites=true&w=majority&appName=message-cluster&ssl=true&authSource=admin}
      database: ${MONGO_DATABASE:bharathva_feed}
      auto-index-creation: false
  
  # NeonDB PostgreSQL Configuration (for user validation)
  datasource:
    url: ${NEONDB_URI:jdbc:postgresql://ep-summer-bar-a1bv6p9u-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require}
    username: ${NEONDB_USERNAME:neondb_owner}
    password: ${NEONDB_PASSWORD:npg_Dtqy63pieawz}
    driver-class-name: org.postgresql.Driver

  # Application Configuration
  application:
    name: feed-service

  # Cache Configuration
  cache:
    type: simple
    cache-names:
      - feedCache

  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET:m7n1lhkmwGNryojEND4kks2nzZypr2S0pGoOAcTqfFIEjXOUByV5BewPKNr0ULNlb7frcStl4MHZO0fNI6g}

  # File upload configuration
  servlet:
    multipart:
      max-file-size: ${SPRING_MULTIPART_MAX_FILE_SIZE:50MB}
      max-request-size: ${SPRING_MULTIPART_MAX_REQUEST_SIZE:100MB}
      enabled: true

# Eureka Discovery Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFERIPADDRESS:true}
    instance-id: ${EUREKA_INSTANCE_INSTANCEID:feed-service:8082}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,metrics}
  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:always}

# Logging
logging:
  level:
    com.bharathva.feed: ${LOGGING_LEVEL_COM_BHARATHVA:INFO}
    root: ${LOGGING_LEVEL_ROOT:INFO}

# Feed Service Configuration
feed:
  migration:
    enabled: ${FEED_MIGRATION_ENABLED:true}
    sample-data: ${FEED_MIGRATION_SAMPLE_DATA:false}

# Cloudinary Configuration
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dqmryiyhz}
  api-key: ${CLOUDINARY_API_KEY:397473723639954}
  api-secret: ${CLOUDINARY_API_SECRET:FM-U9FOM6wm1KWDjS_vc39dngCg}

# File Upload Configuration
app:
  file:
    upload-dir: ${FILE_UPLOAD_DIR:uploads}
    max-size: ${FILE_MAX_SIZE:52428800}  # 50MB in bytes
    allowed-types: ${FILE_ALLOWED_TYPES:image/jpeg,image/png,image/gif,image/webp}


# JWT Configuration
jwt:
  secret: ${JWT_SECRET:m7n1lhkmwGNryojEND4kks2nzZypr2S0pGoOAcTqfFIEjXOUByV5BewPKNr0ULNlb7frcStl4MHZO0fNI6g}

# Auth Service Configuration
auth:
  service:
    url: ${AUTH_SERVICE_URL:http://auth-service:8081}